services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: swiftdb
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      # Jeśli chcesz inicjalne SQL-e, odkomentuj i podaj plik/katalog:
      # - ./init_swiftdb.sql:/docker-entrypoint-initdb.d/001_init.sql:romvn
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d swiftdb"]
      interval: 5s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: showcase
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-db:5432/swiftdb"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      # (opcjonalnie) jawny dialekt hibernata; Spring Boot 3 zwykle wykryje sam
      # SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      # Autogenerowanie schematu (tylko dev!):
      # SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

volumes:
  pg_data: