package edu.bachelor.rest.utils;

import com.syncfusion.ej2.wordprocessor.FormatType;
import com.syncfusion.ej2.wordprocessor.WordProcessorHelper;
import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.UUID;

public class FormatConverter {

  public static byte[] convertDocxToPdfBytesUsingLibreOffice(byte[] docxBytes)
      throws IOException, InterruptedException {

    Path tempDir = Files.createTempDirectory("docx2pdf-");
    Path docxPath = tempDir.resolve(UUID.randomUUID() + ".docx");
    Path pdfPath = tempDir.resolve(docxPath.getFileName().toString().replace(".docx", ".pdf"));

    Files.write(docxPath, docxBytes);

    ProcessBuilder pb =
        new ProcessBuilder(
            "soffice",
            "--headless",
            "--nologo",
            "--nofirststartwizard",
            "--convert-to",
            "pdf",
            "--outdir",
            tempDir.toAbsolutePath().toString(),
            docxPath.toAbsolutePath().toString());

    pb.redirectErrorStream(true);
    Process process = pb.start();

    try (BufferedReader reader =
        new BufferedReader(new InputStreamReader(process.getInputStream()))) {
      while (reader.readLine() != null) {}
    }

    int exitCode = process.waitFor();
    if (exitCode != 0) {
      throw new RuntimeException("LibreOffice failed with exit code " + exitCode);
    }

    if (!Files.exists(pdfPath)) {
      throw new FileNotFoundException("PDF was not generated by LibreOffice");
    }

    byte[] pdfBytes = Files.readAllBytes(pdfPath);

    Files.deleteIfExists(docxPath);
    Files.deleteIfExists(pdfPath);
    Files.deleteIfExists(tempDir);

    return pdfBytes;
  }

  public static String convertDocxToSfdt(byte[] docxBytes) throws Exception {
    String sfdt;
    try (InputStream is = new ByteArrayInputStream(docxBytes)) {
      sfdt = WordProcessorHelper.load(is, FormatType.Docx);
    }
    if (sfdt != null) {
      return sfdt;
    }
    return null;
  }
}
