name: Build Frontend

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ inputs.directory }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs.directory }}
        run: npm ci

      - name: Lint with ESLint
        working-directory: ${{ inputs.directory }}
        run: npm run lint

      - name: Type check
        working-directory: ${{ inputs.directory }}
        run: npm run typecheck

      - name: Check formatting
        working-directory: ${{ inputs.directory }}
        run: npm run format:check

      - name: Run tests
        working-directory: ${{ inputs.directory }}
        run: npm test -- --coverage

      - name: Build project
        working-directory: ${{ inputs.directory }}
        run: npm run build
