name: Build Java

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Prefetch dependencies (go offline)
        run: mvn -B -U -f "${{ inputs.directory }}/pom.xml" dependency:go-offline

      - name: Lint with Checkstyle
        run: mvn -B -f "${{ inputs.directory }}/pom.xml" checkstyle:check || true

      - name: Run tests
        run: mvn -B -f "${{ inputs.directory }}/pom.xml" test

      - name: Package application
        run: mvn -B -f "${{ inputs.directory }}/pom.xml" package -DskipTests
      
      - name: Check formatting
        run: mvn -B -U com.spotify.fmt:fmt-maven-plugin:2.27:check
        working-directory: backend