name: Build Python

on:
  workflow_call:
    inputs:
      directory:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: "3.11"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up cache for pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt', inputs.directory)) }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: ${{ inputs.directory }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest ruff

      - name: Lint with Ruff
        working-directory: ${{ inputs.directory }}
        run: |
          ruff check .

      - name: Run tests
        working-directory: ${{ inputs.directory }}
        run: |
          pytest --maxfail=3 --disable-warnings --tb=short

      - name: Save pip cache
        if: ${{ !cancelled() }}
        uses: actions/cache/save@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles(format('{0}/requirements.txt', inputs.directory)) }}
